# Generated by Django 5.0.6 on 2024-06-22 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0002_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence_details',
            options={'verbose_name_plural': 'Absence Details'},
        ),
        migrations.AlterModelOptions(
            name='attendance_details',
            options={'verbose_name_plural': 'Attendance Details'},
        ),
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name_plural': 'Centers'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='course_attendance',
            options={'verbose_name_plural': 'Course Attendances'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name_plural': 'Divisions'},
        ),
        migrations.AlterModelOptions(
            name='mainbill',
            options={'verbose_name_plural': 'Main Bills'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name_plural': 'Months'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='salesbill',
            options={'verbose_name_plural': 'Sales Bills'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
    ]
